---
title: 'NML502 HW #3'
author: "Elliot Smith, Eugen Hruska, Warum Suriyanarayana"
date: "1/31/2018"
output: pdf_document
---

```{r, echo = FALSE}

## Load packages

suppressMessages(
    library(fields)
)
    
## Load in the data

E <- matrix(nrow = 12, ncol = 12)

E[1,] <- c(1,1,1,1,1,1,1,0,0,0,0,0)
E[2,] <- c(1,1,1,1,1,1,1,0,0,0,0,0)
E[3,] <- c(1,1,0,0,0,0,0,0,0,0,0,0)
E[4,] <- c(1,1,0,0,0,0,0,0,0,0,0,0)
E[5,] <- c(1,1,0,0,0,0,0,0,0,0,0,0)
E[6,] <- c(1,1,1,1,1,1,0,0,0,0,0,0)
E[7,] <- c(1,1,1,1,1,1,0,0,0,0,0,0)
E[8,] <- c(1,1,0,0,0,0,0,0,0,0,0,0)
E[9,] <- c(1,1,0,0,0,0,0,0,0,0,0,0)
E[10,] <- c(1,1,0,0,0,0,0,0,0,0,0,0)
E[11,] <- c(1,1,1,1,1,1,1,0,0,0,0,0)
E[12,] <- c(1,1,1,1,1,1,1,0,0,0,0,0)

H <- matrix(nrow = 12, ncol = 12)

H[1,] <- c(0,0,1,1,0,0,0,0,1,1,0,0)
H[2,] <- c(0,0,1,1,0,0,0,0,1,1,0,0)
H[3,] <- c(0,0,1,1,0,0,0,0,1,1,0,0)
H[4,] <- c(0,0,1,1,0,0,0,0,1,1,0,0)
H[5,] <- c(0,0,1,1,0,0,0,0,1,1,0,0)
H[6,] <- c(0,0,1,1,1,1,1,1,1,1,0,0)
H[7,] <- c(0,0,1,1,1,1,1,1,1,1,0,0)
H[8,] <- c(0,0,1,1,0,0,0,0,1,1,0,0)
H[9,] <- c(0,0,1,1,0,0,0,0,1,1,0,0)
H[10,] <- c(0,0,1,1,0,0,0,0,1,1,0,0)
H[11,] <- c(0,0,1,1,0,0,0,0,1,1,0,0)
H[12,] <- c(0,0,1,1,0,0,0,0,1,1,0,0)

T <- matrix(nrow = 12, ncol = 12)

T[1,] <- c(0,1,1,1,1,1,1,1,1,1,1,0)
T[2,] <- c(0,1,1,1,1,1,1,1,1,1,1,0)
T[3,] <- c(0,0,0,0,0,1,1,0,0,0,0,0)
T[4,] <- c(0,0,0,0,0,1,1,0,0,0,0,0)
T[5,] <- c(0,0,0,0,0,1,1,0,0,0,0,0)
T[6,] <- c(0,0,0,0,0,1,1,0,0,0,0,0)
T[7,] <- c(0,0,0,0,0,1,1,0,0,0,0,0)
T[8,] <- c(0,0,0,0,0,1,1,0,0,0,0,0)
T[9,] <- c(0,0,0,0,0,1,1,0,0,0,0,0)
T[10,] <- c(0,0,0,0,0,1,1,0,0,0,0,0)
T[11,] <- c(0,0,0,0,0,1,1,0,0,0,0,0)
T[12,] <- c(0,0,0,0,0,1,1,0,0,0,0,0)

O <- matrix(nrow = 12, ncol = 12)

O[1,] <- c(0,0,0,1,1,1,1,1,1,0,0,0)
O[2,] <- c(0,0,1,1,1,1,1,1,1,1,0,0)
O[3,] <- c(0,1,1,1,0,0,0,0,1,1,1,0)
O[4,] <- c(0,1,1,1,0,0,0,0,1,1,1,0)
O[5,] <- c(0,1,1,1,0,0,0,0,1,1,1,0)
O[6,] <- c(0,1,1,1,0,0,0,0,1,1,1,0)
O[7,] <- c(0,1,1,1,0,0,0,0,1,1,1,0)
O[8,] <- c(0,1,1,1,0,0,0,0,1,1,1,0)
O[9,] <- c(0,1,1,1,0,0,0,0,1,1,1,0)
O[10,] <- c(0,1,1,1,0,0,0,0,1,1,1,0)
O[11,] <- c(0,0,1,1,1,1,1,1,1,1,0,0)
O[12,] <- c(0,0,0,1,1,1,1,1,1,0,0,0)

M <- matrix(nrow = 12, ncol = 12)

M[1,] <- c(1,1,1,0,0,0,0,0,1,1,1,0)
M[2,] <- c(1,1,1,1,0,0,0,1,1,1,1,0)
M[3,] <- c(1,1,1,1,1,0,1,1,1,1,1,0)
M[4,] <- c(1,1,0,1,1,1,1,1,0,1,1,0)
M[5,] <- c(1,1,0,0,1,1,1,0,0,1,1,0)
M[6,] <- c(1,1,0,0,0,1,0,0,0,1,1,0)
M[7,] <- c(1,1,0,0,0,0,0,0,0,1,1,0)
M[8,] <- c(1,1,0,0,0,0,0,0,0,1,1,0)
M[9,] <- c(1,1,0,0,0,0,0,0,0,1,1,0)
M[10,] <- c(1,1,0,0,0,0,0,0,0,1,1,0)
M[11,] <- c(1,1,0,0,0,0,0,0,0,1,1,0)
M[12,] <- c(1,1,0,0,0,0,0,0,0,1,1,0)

E[E == 0] <- -1
H[H == 0] <- -1
T[T == 0] <- -1
O[O == 0] <- -1
M[M == 0] <- -1

## Load in the err_corr function

err_corr <- function(x, y, mu, n, tol) {
    
    x_orig <- x
    y_orig <- y
    
    x_dims <- dim(x)
    y_dims <- dim(y)
    
    mem_matrix <- matrix(0, nrow = y_dims[1], ncol = x_dims[1])
    
    for (i in 1:n) {
        
        j <- sample(1:x_dims[2])
        x <- x[, j]
        y <- y[, j]
        
        for (k in 1:x_dims[2]) {
            
            mem_matrix <- mem_matrix + mu * (y[,k] - mem_matrix %*% x[,k]) %*% x[,k]
            
        }
        
        if (norm((y - mem_matrix %*% x), "2") <= tol) {
            
            # print("Gradient Search Terminated ===>>> ||y - mem_matrix*x|| <= tol")
            # print(paste0("Number of Iterations = ", n * k))
            mem_matrix <<- mem_matrix
            break
            
        }
        
        mem_matrix <<- mem_matrix
        
    }
    
}

## Vectorize the matrices and prepare the input

E_vec <- as.vector(E)
H_vec <- as.vector(H)
T_vec <- as.vector(T)
O_vec <- as.vector(O)
M_vec <- as.vector(M)

input <- cbind(E_vec, H_vec, T_vec, O_vec, M_vec)

## Set the parameters

mu <- 0.001
n <- 1000
tol <- 0.0000001

## Run the err_corr function to return the memory matrix

err_corr(input, input, mu, n, tol)

```

# Problem 3

## Problem a

* Learning Rate: 0.001
* Max Number of Learning Steps: 1000
* Error Threshold: 0.0000001
* Error Measure: As defined in errcorr.m

### Recall Accuracy

```{r, echo = FALSE}

## Load in a function to rotate the output

rotate <- function(x) t(apply(x, 2, rev))

```

##### Original Input/Output

```{r, echo = FALSE, fig.height = 3}

## Output the original image

image.plot(rbind(rotate(E), rotate(H), rotate(T), rotate(O), rotate(M)), nlevel = 2)

```

##### Memory Recall

```{r, echo = FALSE, fig.height = 3}

## Recall the images from memory

E_recall <- matrix(mem_matrix %*% E_vec, nrow = 12, ncol = 12)
H_recall <- matrix(mem_matrix %*% H_vec, nrow = 12, ncol = 12)
T_recall <- matrix(mem_matrix %*% T_vec, nrow = 12, ncol = 12)
O_recall <- matrix(mem_matrix %*% O_vec, nrow = 12, ncol = 12)
M_recall <- matrix(mem_matrix %*% M_vec, nrow = 12, ncol = 12)

## Rebuild the image

image.plot(rbind(rotate(E_recall), rotate(H_recall), rotate(T_recall), rotate(O_recall), rotate(M_recall)), nlevel = 2)

```
















